# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fake-app
  template:
    metadata:
      labels:
        app: fake-app
    spec:
      containers:
        - name: argocd-fake-app
          image: argocdfakeapp
          ports:
            - containerPort: 80
